version: '3'
volumes:
  pgdata:
services:
  database:
    image: savicsorg/dhis2-postgresql9.5:1latest
    restart: always
    environment:
      POSTGRES_USER: cesarie
      POSTGRES_DB: dhis2
      POSTGRES_PASSWORD: dhis
    volumes:
     - "pgdata:/var/lib/postgresql/data/"
    ports:
     - "5465:5432"
    links:
     - web
  web:
    image: savicsorg/dhis2-tomcat7jdk8:1latest
    restart: always
    ports:
      - "8082:8080"
